# Generated by Django 5.2.17 on 2026-09-26 08:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_courseteachingassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='core.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('course__code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RubricVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=160)),
                ('section_name', models.CharField(max_length=120)),
                ('task_type', models.CharField(max_length=80)),
                ('target_level_min', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('target_level_max', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('source_reference', models.CharField(max_length=255)),
                ('source_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('retired', 'Ngừng sử dụng')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rubric_versions', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.rubric')),
            ],
            options={
                'ordering': ('rubric_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rubric_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='core.rubricversion')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RubricAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Tạo nháp'), ('updated', 'Cập nhật nháp'), ('revision_created', 'Tạo phiên bản mới'), ('published', 'Xuất bản'), ('retired', 'Ngừng sử dụng')], max_length=24)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_audit_events', to=settings.AUTH_USER_MODEL)),
                ('rubric_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.rubricversion')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CriterionLevelDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('text', models.TextField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='core.rubriccriterion')),
            ],
            options={
                'ordering': ('criterion__position', 'level'),
                'constraints': [models.UniqueConstraint(fields=('criterion', 'level'), name='unique_criterion_level_descriptor')],
            },
        ),
        migrations.AddConstraint(
            model_name='rubricversion',
            constraint=models.UniqueConstraint(fields=('rubric', 'version'), name='unique_rubric_version_number'),
        ),
        migrations.AddConstraint(
            model_name='rubricversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='rubric_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='rubricversion',
            constraint=models.CheckConstraint(condition=models.Q(('target_level_min', ''), ('target_level_max', ''), ('target_level_min__lte', models.F('target_level_max')), _connector='OR'), name='rubric_level_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric_version', 'position'), name='unique_rubric_criterion_position'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='rubric_criterion_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('max_points__isnull', True), ('max_points__gt', 0), _connector='OR'), name='rubric_criterion_points_positive'),
        ),
    ]
