# Generated by Django 5.2.17 on 2026-09-26 09:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rubric_rubricversion_rubriccriterion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=160)),
                ('source_reference', models.CharField(max_length=255)),
                ('source_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('retired', 'Ngừng sử dụng')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_blueprint_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('blueprint_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='BlueprintSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=160)),
                ('seed', models.PositiveBigIntegerField()),
                ('blueprint_snapshot', models.JSONField()),
                ('candidate_pool_snapshot', models.JSONField()),
                ('exclusion_snapshot', models.JSONField()),
                ('selected_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_samples', to=settings.AUTH_USER_MODEL)),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.blueprintversion')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BlueprintAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Tạo nháp'), ('updated', 'Cập nhật nháp'), ('revision_created', 'Tạo phiên bản mới'), ('published', 'Xuất bản'), ('retired', 'Ngừng sử dụng')], max_length=24)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_audit_events', to=settings.AUTH_USER_MODEL)),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.blueprintversion')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExamBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprints', to='core.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_blueprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('course__code', 'id'),
            },
        ),
        migrations.AddField(
            model_name='blueprintversion',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.examblueprint'),
        ),
        migrations.CreateModel(
            name='BlueprintSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('section_name', models.CharField(max_length=120)),
                ('task_type', models.CharField(max_length=64)),
                ('question_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target_level_min', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('target_level_max', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('language', models.CharField(default='en', max_length=16)),
                ('prep_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('response_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rubric_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_slots', to='core.rubricversion')),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.blueprintversion')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('blueprint_version', 'position'), name='unique_blueprint_slot_position'), models.UniqueConstraint(fields=('blueprint_version', 'section_name'), name='unique_blueprint_slot_section'), models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='blueprint_slot_position_positive'), models.CheckConstraint(condition=models.Q(('question_count__gte', 1)), name='blueprint_slot_question_count_positive'), models.CheckConstraint(condition=models.Q(('response_seconds__gte', 1)), name='blueprint_slot_response_seconds_positive'), models.CheckConstraint(condition=models.Q(('target_level_min__lte', models.F('target_level_max'))), name='blueprint_slot_level_range_ordered')],
            },
        ),
        migrations.AddConstraint(
            model_name='blueprintversion',
            constraint=models.UniqueConstraint(fields=('blueprint', 'version'), name='unique_blueprint_version_number'),
        ),
        migrations.AddConstraint(
            model_name='blueprintversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='blueprint_version_positive'),
        ),
    ]
