# Generated by Django 5.2.17 on 2026-09-26 09:29

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blueprintversion_blueprintsample_blueprintauditevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('response_seconds', models.PositiveSmallIntegerField()),
                ('ai_model', models.CharField(max_length=100)),
                ('questions', models.JSONField()),
                ('status', models.CharField(choices=[('in_progress', 'Đang làm'), ('submitted', 'Đã nộp')], default='in_progress', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_attempts', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveSmallIntegerField()),
                ('audio', models.FileField(upload_to=core.models.practice_audio_upload_path)),
                ('audio_extension', models.CharField(max_length=5)),
                ('content_type', models.CharField(max_length=32)),
                ('duration_seconds', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.practiceattempt')),
            ],
            options={
                'ordering': ('question_index',),
            },
        ),
        migrations.AddConstraint(
            model_name='practiceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gte', 1)), name='practice_question_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='practiceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('response_seconds__gte', 1)), name='practice_response_seconds_positive'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_index'), name='unique_practice_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.CheckConstraint(condition=models.Q(('question_index__gte', 1)), name='practice_answer_index_positive'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 1)), name='practice_answer_duration_positive'),
        ),
    ]
