from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/student/", views.student_dashboard, name="dashboard_student"),
    path("dashboard/teacher/", views.teacher_dashboard, name="dashboard_teacher"),
    path("dashboard/admin/", views.admin_dashboard, name="dashboard_admin"),
    path("dashboard/admin/accounts/", views.demo_accounts, name="demo_accounts"),
    path("dashboard/admin/accounts/new/", views.demo_account_create, name="demo_account_create"),
    path("dashboard/admin/accounts/<str:username>/edit/", views.demo_account_edit, name="demo_account_edit"),
    path("practice/new/", views.practice_create, name="practice_create"),
    path("practice/preflight/", views.practice_preflight, name="practice_preflight"),
    path("practice/preflight/complete/", views.practice_preflight_complete, name="practice_preflight_complete"),
    path("practice/preflight/network/", views.network_probe, name="network_probe"),
    path("practice/start/", views.practice_start, name="practice_start"),
    path("practice/<int:attempt_id>/", views.practice_detail, name="practice_detail"),
    path("practice/<int:attempt_id>/answer/", views.practice_answer_upload, name="practice_answer_upload"),
    path("practice/<int:attempt_id>/submit/", views.practice_submit, name="practice_submit"),
    path("practice/review/<int:attempt_id>/", views.practice_review, name="practice_review"),
    path("practice/answer/<int:answer_id>/audio/", views.practice_answer_audio, name="practice_answer_audio"),
    path("exam/version/<int:version_id>/start/", views.exam_start, name="exam_start"),
    path("exam/preflight/", views.exam_preflight, name="exam_preflight"),
    path("exam/preflight/complete/", views.exam_preflight_complete, name="exam_preflight_complete"),
    path("exam/preflight/network/", views.exam_network_probe, name="exam_network_probe"),
    path("exam/preflight/begin/", views.exam_preflight_begin, name="exam_preflight_begin"),
    path("exam/<int:attempt_id>/", views.exam_detail, name="exam_detail"),
    path("exam/<int:attempt_id>/answer/", views.exam_answer_upload, name="exam_answer_upload"),
    path("exam/<int:attempt_id>/submit/", views.exam_submit, name="exam_submit"),
    path("exam/answer/<int:answer_id>/audio/", views.exam_answer_audio, name="exam_answer_audio"),
    path("exam/review/<int:attempt_id>/", views.exam_review, name="exam_review"),
    path("exam/review/", views.exam_review_queue, name="exam_review_queue"),
    path("exam/review/<int:attempt_id>/claim/", views.exam_review_claim, name="exam_review_claim"),
    path("question-bank/", views.question_bank, name="question_bank"),
    path("question-bank/new/", views.question_create, name="question_create"),
    path("question-bank/import/", views.question_import, name="question_import"),
    path("question-bank/<int:question_id>/", views.question_detail, name="question_detail"),
    path("question-bank/version/<int:version_id>/edit/", views.question_edit, name="question_edit"),
    path("question-bank/version/<int:version_id>/submit/", views.question_submit_review, name="question_submit_review"),
    path("question-bank/version/<int:version_id>/review/", views.question_review, name="question_review"),
    path("question-bank/version/<int:version_id>/revision/", views.question_new_revision, name="question_new_revision"),
    path("question-bank/version/<int:version_id>/retire/", views.question_retire, name="question_retire"),
    path("rubrics/", views.rubric_bank, name="rubric_bank"),
    path("rubrics/new/", views.rubric_create, name="rubric_create"),
    path("rubrics/<int:rubric_id>/", views.rubric_detail, name="rubric_detail"),
    path("rubrics/version/<int:version_id>/edit/", views.rubric_edit, name="rubric_edit"),
    path("rubrics/version/<int:version_id>/publish/", views.rubric_publish, name="rubric_publish"),
    path("rubrics/version/<int:version_id>/revision/", views.rubric_new_revision, name="rubric_new_revision"),
    path("rubrics/version/<int:version_id>/retire/", views.rubric_retire, name="rubric_retire"),
    path("blueprints/", views.blueprint_bank, name="blueprint_bank"),
    path("blueprints/new/", views.blueprint_create, name="blueprint_create"),
    path("blueprints/<int:blueprint_id>/", views.blueprint_detail, name="blueprint_detail"),
    path("blueprints/version/<int:version_id>/edit/", views.blueprint_edit, name="blueprint_edit"),
    path("blueprints/version/<int:version_id>/publish/", views.blueprint_publish, name="blueprint_publish"),
    path("blueprints/version/<int:version_id>/revision/", views.blueprint_new_revision, name="blueprint_new_revision"),
    path("blueprints/version/<int:version_id>/retire/", views.blueprint_retire, name="blueprint_retire"),
    path("blueprints/version/<int:version_id>/sample/", views.blueprint_sample, name="blueprint_sample"),
    path("health/", views.health, name="health"),
    path("health/live/", views.health, name="health_live"),
    path("health/ready/", views.readiness, name="health_ready"),
]
